spring:
  datasource:
    url: jdbc:mysql://192.168.31.229:3306/springsecurity?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: springsecurity
    password: springsecurity
    driver-class-name: com.mysql.cj.jdbc.Driver

  redis:
    host: 192.168.31.229
    port: 6379
    password: 123456
    timeout: 10000
    lettuce:
      pool:
        max-active: 8
        # 连接池最大阻塞时间（使用负值表示没有限制）
        max-wait: -1ms
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池中的最小空闲连接
        min-idle: 0
jwtConfig:
  # 默认7天过期 单位为毫秒
  expirationTime: 604800000
debug: false
mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
