spring:
  datasource:
    url: jdbc:mysql://192.168.31.229:3306/springsecurity?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: springsecurity
    password: springsecurity
    driver-class-name: com.mysql.cj.jdbc.Driver

  redis:
    port: 6379
    password: 123456
    host: 192.168.31.229

jwtConfig:
  # 默认7天过期
  expirationTime: 1000*60*60*24*7
